### ISSUE TITLE
ユースケース図にユースケースでないものがある

### ISSUE THREAD

**Issue by r-kurose** [rsdlab/PresentationManageSystem#2]
PresentationRobotSystem_SysML.pdf のユースケース図を見ました。

ユーザーは何かを得るためにシステムを使います。
ユースケース図は、システムを使って「ユーザーが何をするか」ということを説明するものです。
このシステムを使って「発表の代行をする」のはわかります。
一方で、「アームを制御する」ことがしたい人はいないでしょう。
`<<include>>`で記述されているものはユースケースでは無く、開発者が作る機能ではないでしょうか。

**Comment by hiroyasu-tsuji** [comment]
r-kurose様
コメントありがとうございます。

ご指摘の通り、設計したユースケース図ではロボット側からの機能が存在していました。
よって、それらの機能を削除し、再設計しましたのでもう一度ご確認いただければ幸いです。

**Comment by r-kurose** [comment]
「聴講者の顔の位置を認識する」などがなぜ残ったのかなどは疑問ではありますが、
自身の判断で不要と思った部分を削除されたようなのでクローズします。
ありがとうございました。
